server {
    listen 80;

    # FRONTEND
    location / {
        proxy_pass http://host.docker.internal:5173;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # BACKEND (IMPORTANT: trailing slash matters)
    location /api/ {
        proxy_pass http://host.docker.internal:8080/;
    }

    # KEYCLOAK
    location /auth/ {
        proxy_pass http://host.docker.internal:8082/;
    }
}